solution: clrzmq4.mono.sln
language: csharp
mono: latest
sudo: required

matrix:
  include:
    - os: linux
      dist: xenial

    - os: osx
      osx_image: xcode9.4
#      osx_image: xcode7.3

before_install:
  - sudo apt-get install -y libzmq5 
#  - chmod a+x ./travis.preinstall.sh

install:
  - nuget restore clrzmq4.mono.sln
#  - ./travis.preinstall.sh

before_script:
  - msbuild clrzmq4.mono.sln /p:Configuration=Release
#  - chmod a+x ./build.sh
#  - ./build.sh

script:
  - mono bin/Release/ZGuideExamples.exe EAgain
  - mono bin/Release/ZGuideExamples.exe Espresso
  - mono bin/Release/ZGuideExamples.exe AsyncSrv
  - mono bin/Release/ZGuideExamples.exe SuiSnail
