version: 1.0.{build}
before_build:
- cmd: nuget restore clrzmq4.VS.sln
configuration:
- Release
environment:
  COVERALLS_REPO_TOKEN:
    secure: yCIV3arujsrEYPNrM/wQSs1HQThuA8lSzZ9hTcv28fhgYu3aWyPkneGdaIDElJYp
nuget:
  project_feed: true
build:
  project: clrzmq4.VS.sln
  verbosity: minimal
after_build:
  cmd: nuget pack ZeroMQ.nuspec
test_script:
- ps: .\test.ps1
after_test:
- ps: .\upload_coverage.ps1
artifacts:
- path: results.xml
- path: '**\ZeroMQ*.nupkg'
