version: "{build}"
platform: x64
configuration: Release

#image:
#- Visual Studio 2017

init:
- cmd: msbuild /version

install:
- cmd: vcpkg install zeromq:x64-windows
#- cmd: vcpkg integrate install
- cmd: nuget restore clrzmq4.vs.sln

before_build:
- cmd: call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
build:
  project: clrzmq4.vs.sln

test_script:
- cmd: .\bin\Release\ZGuideExamples.exe Version
- cmd: .\bin\Release\ZGuideExamples.exe EAgain
- cmd: .\bin\Release\ZGuideExamples.exe Espresso

