#version: 4.0.0.{build}
configuration: Release
environment:
  COVERALLS_REPO_TOKEN:
    secure: yCIV3arujsrEYPNrM/wQSs1HQThuA8lSzZ9hTcv28fhgYu3aWyPkneGdaIDElJYp
nuget:
  project_feed: true

before_build:
- cmd: nuget restore clrzmq4.vs.sln
build:
  project: clrzmq4.vs.sln
#  verbosity: minimal
#after_build: 
#  cmd: nuget pack ZeroMQ.nuspec -Symbols -Verbosity detailed # -Version %APPVEYOR_BUILD_VERSION% -Suffix unreleased 

test_script:
- cmd: bin/Release/ZGuideExamples.exe EAgain
- cmd: bin/Release/ZGuideExamples.exe Espresso
#- ps: .\test.ps1
#after_test:
#- ps: .\upload_coverage.ps1
#artifacts:
#- path: results.xml
#- path: '**\ZeroMQ*.nupkg'
