version: 1.0.{build}
before_build:
- cmd: nuget restore clrzmq4.VS.sln
environment:
  COVERALLS_REPO_TOKEN:
    secure: yCIV3arujsrEYPNrM/wQSs1HQThuA8lSzZ9hTcv28fhgYu3aWyPkneGdaIDElJYp
build:
  project: clrzmq4.VS.sln
  verbosity: minimal
test_script:
- cmd: test.ps1
