version: 1.0.{build}
before_build:
- cmd: nuget restore clrzmq4.VS.sln
environment:
  COVERALLS_REPO_TOKEN:
    secure: yCIV3arujsrEYPNrM/wQSs1HQThuA8lSzZ9hTcv28fhgYu3aWyPkneGdaIDElJYp
nuget:
  account_feed: true
  project_feed: true
build:
  project: clrzmq4.VS.sln
  publish_nuget: true             # package projects with .nuspec files and push to artifacts
  publish_nuget_symbols: true     # generate and publish NuGet symbol packages
  verbosity: minimal
test_script:
- ps: .\test.ps1
after_test:
- ps: .\upload_coverage.ps1
